### PR TITLE
Added audio-only mode

### PR DESCRIPTION
**Pull request by Dev-Mikko**
Thanks to this pull request, the room server will be able to handle audio-only communication. When a peer is using the audio-only mode, no video consumer will be created on the server side in order to do not waste resources.

### CODE REVIEW

**Comment by pnts-se** [comment]
Perhaps we could add unit-tests to verify that video consumers are not created?
I can do it and attach to this PR.

**Comment by Dev-Mikko** [comment]
@pnts-se for me it is OK. You can do that.

**Comment by pnts-se** [comment]
@Dev-Mikko done.

**Comment by Dev-Mikko** [comment]
@pnts-se great. Thank you

**Comment by pnts-se** [comment]
@Dev-Mikko I'll do code review of this PR next week.

**Review by pnts-se — APPROVED** [review]
LGTM

**Pull request merged**
